# Title of the site
title: "Portfolio-Jekyll"
# Description of the site
description: "Simple theme"

# The subpath of your site - use "" if you're hosting a blog at the root level
baseurl: "/portfolio-jekyll"
# The base hostname & protocol for your site
url: "jsidrach.github.io"

# Do not publish these files
exclude: ["README.md", "Gemfile", "Gemfile.lock", "LICENSE"]

# Sass configuration - compress resulting stylesheet
sass:
  style: compressed

# Projects collection
collections:
  - projects

# Navigation bar
navbar:
  - name: GitHub
    link: https://github.com/jsidrach/portfolio-jekyll
    icon: repo.svg

  - name: LinkedIn
    link: https://linkedin.com/in/
    icon: jobs.svg

  - name: Resume
    link: /public/resume.pdf
    icon: resume.svg

  - name: Mail
    link: mailto:example@mail.com
    icon: mail.svg

# Compress html
compress_html:
  clippings: all
  comments: all
  startings: []
  endings: []
  ignore:
    envs: []
  blanklines: false
  profile: false
